language: perl6

perl6:
  - nom
  - latest
  - "2017.03"
  - "2017.04"

os:
  - linux

install:
  - rakudobrew build zef
  - zef install --depsonly .

script: AUTHOR_TESTING=1 prove -v -e "perl6 -Ilib" t/
