language: perl6
os:
  - linux
  - osx
dist: trusty
sudo: required
osx_image: xcode8.3
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libgeoip1 geoip-database-contrib ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ln -s /usr/share/GeoIP/GeoLiteCityv6.dat /usr/share/GeoIP/GeoIPCityv6.dat ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install geoip geoipupdate ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then geoipupdate -f etc/GeoIP.conf; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ln -s /usr/local/var/GeoIP/GeoLiteCityv6.dat /usr/local/var/GeoIP/GeoIPCityv6.dat ; fi
