language: perl6

perl6:
  - latest
  - nom
  - "2017.03"
  - "2017.04"

os:
  - linux

install:
  - rakudobrew build zef
  - zef install --depsonly .

script: AUTHOR_TESTING=1 prove -v -e "perl6 -Ilib" t/

notifications:
  irc:
    channels:
      - "irc.darenet.org#scriptkitties"
    on_success: change
    on_failure: always
    template:
      - "Hash::Merge build %{result}. %{author} '%{commit_message}' â†’ %{build_url}"

