branches:
  only:
    - master

language: perl6

perl6:
  - latest

# sudo required for libxxhash installation
sudo: required

before_install:
  # install libxxhash into /usr/lib/libxxhash.so
  - curl https://codeload.github.com/Cyan4973/{xxHash}/{tar.gz}/{r42} -o "#1-#3.#2"
  - tar xvzf xxHash-r42.tar.gz
  - cd xxHash-r42
  - mkdir build && pushd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr ../cmake_unofficial/
  - make all
  - popd
  - sudo make install -C build/
  - cd $TRAVIS_BUILD_DIR
