language: "perl"

services:
  - docker

env:
  - TEST=prove
  - TEST=api
  - TEST=bootstrap:alpine
  - TEST=bootstrap:amazon
  - TEST=bootstrap:archlinux
  - TEST=bootstrap:centos
  - TEST=bootstrap:debian
  - TEST=bootstrap:fedora
  - TEST=bootstrap:funtoo
  - TEST=bootstrap:ubuntu
    
install:
  - cpanm https://github.com/melezhik/outthentic.git
  - cpanm https://github.com/melezhik/sparrow.git
  - sparrow index update
  - sparrow plg install rakudo-install
  - sparrow plg run rakudo-install --param user_install=on --param sudo=on --param url=https://github.com/nxadm/rakudo-pkg/releases/download/2017.09.1%2B2/perl6-rakudo-moarvm-debian8.7_20170900-01_amd64.deb
  - export PATH=$PATH:$HOME/.perl6/bin:/opt/rakudo/bin
  - zef install .
  - zef install Sparrowdo::Sparrow::Update

script:
  - sh ./.travis.d/run.sh "$TEST"
