language: perl6
perl6:
    - latest

install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq
    - sudo apt-get -qq install g++-4.8
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
    - rakudobrew build-panda
    - panda --notests installdeps .
    - panda --notests installdeps .
    - panda install LibraryMake

script: panda-build && prove -e perl6 t

