# version for 'time'
sudo: true
language: perl6
perl6:
    - latest

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y time

install:
    - rakudobrew build-zef
    # the following command avoids double-testing of the target module:
    - zef --deps-only install .
