branches:
    only:
        - master

language: perl6

perl6:
    - latest

# sudo required for libxxhash installation
sudo: required

before_install:
    # install libxxhash into /usr/lib/libxxhash.so
    - curl https://codeload.github.com/Cyan4973/{xxHash}/{tar.gz}/{v0.6.4} -o "#1-#3.#2"
    - tar xvzf xxHash-v0.6.4.tar.gz
    - cd xxHash-0.6.4
    - make lib
    - sudo make PREFIX="/usr" install
    - cd $TRAVIS_BUILD_DIR
